project:
  type: book

book:
  title: "SG0002"
  author: "Izar de Villasante"
  date: "1/31/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - integrative_analysis.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    self-contained: true
    embed-resources: true
    page-layout: full
    theme: cosmo
    grid:
      sidebar-width: 300px
      body-width: 1200px
      margin-width: 100px
      gutter-width: 1.5rem
# 
# geometry:
#   - left=.5in
#   - textwidth=4.5in
#   - marginparsep=.25in
#   - marginparwidth=1.25in


