project:
  type: book

book:
  title: "SG0002"
  author: "Jane Doe"
  date: "1/31/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - integrative_analysis.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo




